apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modify-nodes
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - delete
      - edit
      - taint
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: modify-nodes-to-sa
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
    namespace: default
roleRef:
  kind: ClusterRole
  name: modify-nodes
  apiGroup: rbac.authorization.k8s.io